modules:
  # connectionString format -> mongodb+srv://admin:<password>@cluster0.zfbz8.mongodb.net/<dbname>?retryWrites=true&w=majority
  database:
    # Optional
    username: ""
    # Optional
    password: "123DenkHetNiet"
    # Required
    hostname: ""
    # Optional
    port: ""
    # Optional
    dbname: ""